DnaFragment/Models/Api/LrProducts/AllLrProductsApiRequestModel.cs
namespace DnaFragment.Models.Api.LrProducts
{
    public class AllLrProductsApiRequestModel
    {
        public string Brand { get; init; }

        public int ProductsPerPage { get; init; } = 6;

        public string SearchTerm { get; init; }

        public LrProductSorting Sorting { get; init; }

        public int CurrentPage { get; init; } = 1;

        public int TotalProducts { get; init; }
    }
}

DnaFragment/Models/LrProducts/AddNewInfoProductFormModel.cs
namespace DnaFragment.Models.LrProducts
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using DnaFragment.Services.LrProducts.Models;

    public class AddNewInfoProductFormModel
    {      
        public List<LrProductDetailsServiceModel> Products { get; init; }

        [Range(1, 100)]
        public int ProductsCount { get; init; } = 1;

        public bool  ProductsCountIsNotEmpty { get; init; }

        public decimal? Amount { get; init; }

        public decimal PercentageDiscount { get; init; }
    }
}

DnaFragment/Models/LrProducts/AddProductFormModel.cs
namespace DnaFragment.Models.LrProducts
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;  
    using static Data.DataConstants.LrProductConst;
    using static Data.DataConstants.DefaultConstants;
    using DnaFragment.Services.LrProducts.Models;

    public class AddProductFormModel
    {
        [Required]
        [StringLength(ModelMaxLength, MinimumLength = ModelMinLength)]
        public string Model { get; init; }

        [Required]
        [StringLength(MaxVolume, MinimumLength =MinVolume)]
        public string PackagingVolume { get; init; }

        [Range(0, double.MaxValue)]
        public decimal Price { get; set; }

        [Required]
        [StringLength(
        DescriptionMaxLength,
        MinimumLength = DescriptionMinLength,
        ErrorMessage = "The field Description must be a string with a minimum length of {2}.")]
        public string Description { get; set; }


        [Required]
        [StringLength(
        ChemicalDescriptionMaxLength,
        MinimumLength = DescriptionMinLength,
        ErrorMessage = "The field Description must be a string with a minimum length of {2}.")]
        public string ChemicalIngredients { get; set; }

        public int Year { get; init; }

        [Display(Name = "Image URL")]
        [Required]
        [Url]
        public string Image { get; init; }

        [Required]
        [MaxLength(PlateNumberMaxLength)]
        public string PlateNumber { get; set; }

        [Display(Name = "Category")]
        public int CategoryId { get; init; }

        public IEnumerable<LrCategoryServiceModel> Categories { get; set; }
       
    }
}

DnaFragment/Models/LrProducts/AddProductUpdateFormModel.cs
namespace DnaFragment.Models.LrProducts
{    
    using System.ComponentModel.DataAnnotations;
    using static Data.DataConstants.LrProductConst;
    using static Data.DataConstants.DefaultConstants;
    using System.Collections.Generic;
    using DnaFragment.Services.LrProducts.Models;

    public class AddProductUpdateFormModel
    {
        [Range(0, double.MaxValue)]
        public decimal Price { get; set; }

        [Required]
        [StringLength(
        DescriptionMaxLength,
        MinimumLength = DescriptionMinLength,
        ErrorMessage = "The field Description must be a string with a minimum length of {2}.")]
        public string Description { get; set; }

        [Display(Name = "Category")]
        public int CategoryId { get; init; }

        public IEnumerable<LrCategoryServiceModel> Categories { get; set; }

        public int UserId { get; init; }
    }
}

DnaFragment/Models/LrProducts/AllProductsQueryModel.cs
namespace DnaFragment.Models.LrProducts
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using DnaFragment.Services.LrProducts.Models;

    public class AllProductsQueryModel
    {
        public const int ProductsPerPage = 6;

        public string Brand { get; init; }

        [Display(Name = "Search by text")]
        public string SearchTerm { get; init; }

        public LrProductSorting Sorting { get; init; }

        public int CurrentPage { get; init; } = 1;

        public int TotalProducts { get; set; }

        public IEnumerable<string> Brands { get; set; }

        public IEnumerable<LrProductServiceModel> LrProducts { get; set; }

        public bool CategoryAny { get; set; }
    }
}

DnaFragment/Models/LrProducts/BagsInformationsModel.cs
namespace DnaFragment.Models.LrProducts
{
    using System.ComponentModel.DataAnnotations;
    using static DnaFragment.Data.DataConstants.LrUserConst;
    public class BagsInformationsModel
    {
        [RegularExpression(@"[\w\s]{5,}[\d]+", ErrorMessage = "Address is not valid!")]
        public string Address { get; init; }

        [RegularExpression(@"^[\w\s]{3,}$", ErrorMessage = "City is not valid!")]
        public string City { get; set; }

        [Display(Name = "Phone Number")]
        [StringLength(PhoneNumberMaxLength, MinimumLength = PhoneNumberMinLength)]
        public string PhoneNumber { get; set; }

    }
}

DnaFragment/Areas/Admin/Controllers/LrProductsController.cs
namespace DnaFragment.Areas.Admin.Controllers
{
    using DnaFragment.Models.LrProducts;
    using DnaFragment.Services.LrProducts;
    using Microsoft.AspNetCore.Mvc;

    public class LrProductsController : AdminController
    {
        
        private readonly ILrProductsService lrProducts;
        public LrProductsController(ILrProductsService lrProducts)
        {
            this.lrProducts = lrProducts;
            
        }

      
        public IActionResult Start()
        {
            lrProducts.StartLrProduktDb();

            return Redirect("~/LrProducts/All");
        }
        
        public IActionResult Add(int id)
        {         
            if (id != 0)
            {
                var product = lrProducts.Details(id);

                return View(new AddProductFormModel
                {
                    Model = product.Model,
                    Description = product.Description,
                    ChemicalIngredients = product.ChemicalIngredients,
                    Price = product.Price,
                    PlateNumber = product.PlateNumber,
                    Categories = lrProducts.AllCategories()
                });
            }
            else
            {
                return View(new AddProductFormModel
                {
                    Categories = lrProducts.AllCategories()
                });
            }
        }

        [HttpPost]      
        public IActionResult Add(int id, AddProductFormModel lrProduct)
        {           
            if (!lrProducts.CategoryExsists(lrProduct.CategoryId))
            {
                this.ModelState.AddModelError(nameof(lrProduct.CategoryId), "Category does not exist.");
            }

            if (!ModelState.IsValid)
            {
                lrProduct.Categories = this.lrProducts.AllCategories();
                return View(lrProduct);
            }

            if (id != 0)
            {
                lrProducts.Update(
                lrProduct.Description,
                lrProduct.Price,
                lrProduct.Image,
                lrProduct.PlateNumber,
                id,
                lrProduct.CategoryId);
            }
            else
            {
                lrProducts.Create(lrProduct.Model,
                lrProduct.PackagingVolume,
                lrProduct.ChemicalIngredients,
                lrProduct.Description,
                lrProduct.Price,
                lrProduct.Year,
                lrProduct.Image,
                lrProduct.PlateNumber,
                lrProduct.CategoryId);
            }

            return Redirect("~/LrProducts/All");
        }

    }
}

DnaFragment/Views/LrProducts/All.cshtml
@model AllProductsQueryModel

@{
    ViewBag.Title = "LR";
}
 <hr class="bg-primary w-75">
   @if (!Model.LrProducts.Any() && User.IsAdmin())
    {
<form class="mx-auto w-50" size="3">
    <div class="alert alert-danger">
        <strong>Please import products by category in the database!</strong><button type="button" class="close text-white" data-dismiss="alert">&times;</button>
    </div>
</form>
    } 
    else if (!Model.LrProducts.Any() && !User.IsAdmin())
    {
<form class="mx-auto w-50" size="3">
    <div class="alert alert-secondary  small ">
        <strong>We are currently loading the new batch from the plant in Germany!</strong><button type="button" class="close text-white" data-dismiss="alert">&times;</button>
    </div>
</form>
    }
 <hr class="bg-primary w-50">
 <hr class="bg-primary w-25">
 
 <div class="container w-75">
     <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
         <div class="carousel-inner">
             <div class="carousel-item active">
                 <img class="d-block w-100" src="https://wallpapermemory.com/uploads/641/perfume-background-hd-2560x1440-301965.jpg" alt="Responsive image">
             </div>
             <div class="carousel-item">
                 <img class="d-block w-100" src="http://wallpaperstock.net/purple-flowers_wallpapers_55102_1920x1080.jpg" alt="Responsive image">
             </div>
             <div class="carousel-item">
                 <img class="d-block w-100" src="https://www.teahub.io/photos/full/306-3063216_benefits-of-aloe-vera-aloe-vera-gel.jpg" alt="Responsive image">
             </div>

         </div>
     </div>
    @if (User.IsAdmin())
     {
     <ul class="list-group list-group-flush " >
         <li class="btn-group btn-group d-flex justify-content-center " role="group" aria-label="Button group example" method="post">
            @if (!Model.CategoryAny)
             {
                <a asp-area="Admin" asp-controller="Categories" asp-action="Start" class="btn btn-primary text-xl-center  text-break">Category Start</a>
             }
            @if (!Model.LrProducts.Any() && Model.CategoryAny)
             {
                 <a class="btn btn-success text-xl-center text-break"
                  asp-area="Admin" asp-controller="LrProducts"
                  asp-action="Start">
                   LrProdukt Start
                 </a> 
             }
         </li>
     </ul>
     }
 </div>  
      <hr class="bg-primary w-25">
      <hr class="bg-primary w-50">
      <hr class="bg-primary w-75">
      <form method="get">
          <div class="row">
              <div class="form-group col-md-4">
                  <div class="form-group">
                      <label asp-for="Brand"></label>
                      <h class="text-success">•</h>
                      <select asp-for="Brand" class="form-control">
                          <option value="">All</option>

                          @foreach (var brand in Model.Brands)
                          {
                              <option value="@brand">@brand</option>
                          }
                      </select>
                  </div>
              </div>             
              <div class="form-group col-md-4">
                  <label asp-for="SearchTerm"></label>
                  <h class="text-success">•</h>
                  <input asp-for="SearchTerm" class="form-control" placeholder="парфюм,крем,гел">
              </div>
              <div class="form-group col-md-4">
                  <div class="form-group">
                      <label asp-for="Sorting"></label>
                      <h class="text-success">•</h>
                      <select asp-for="Sorting" class="form-control">
                          <option value="0" selected>Volume</option>
                          <option value="1">Brand And Price</option>
                      </select>
                  </div>
              </div>
          </div>
      </form>

      @{ var previousPage = Model.CurrentPage - 1;
       if (previousPage < 1)
       {
           previousPage = 1;
       }
       var maxPage = Math.Ceiling((double)Model.TotalProducts / AllProductsQueryModel.ProductsPerPage); }

      <div class="row mb-4">
          <div class="col-md-12">

              <a type="button" class="btn btn-primary  float-left  @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
                 asp-controller="LrProducts"
                 asp-action="All"
                 asp-route-currentPage="@previousPage"
                 asp-route-brand="@Model.Brand"
                 asp-route-searchTerm="@Model.SearchTerm"
                 asp-route-sorting="@((int)Model.Sorting)"><< </a>

              <a class="btn btn-primary  float-right  @(Model.CurrentPage == maxPage ? "disabled" : string.Empty)"
                 asp-controller="LrProducts"
                 asp-action="All"
                 asp-route-currentPage="@(Model.CurrentPage + 1)"
                 asp-route-brand="@Model.Brand"
                 asp-route-searchTerm="@Model.SearchTerm"
                 asp-route-sorting="@((int)Model.Sorting)">>></a>
          </div>
      </div>

      @if (!Model.LrProducts.Any() && !User.IsAdmin())
      {
         <h3 class="text-center">No products found by the given criteria!</h3>
      }

  <div class="row justify-content-center">
     @foreach (var product in Model.LrProducts)
      {
  <div class=" col-md-4 ">
      <div class="form-group card mb-3 ">
          <a class="btn btn-outline-warning font-italic text-sm text-break"
             asp-controller="LrProducts"
             asp-action="Details"
             asp-route-id="@product.Id">
              @product.Model
          </a>
         <img class="card-img-top" src="@product.PictureUrl" alt="@product.Price" title="LR">
          <div class="card-body text-center">
              <ul class="list-group list-group-flush ">
                  <li class="list-group-item text-xl-center text-white">@product.Price lv.</li>
              </ul>
              <ul class="list-group list-group-flush ">
                  <li class="btn-group btn-group d-flex justify-content-center " role="group" aria-label="Button group example">
                     
                      @if (User.IsAdmin())
                      {
                      <a class="btn btn-primary text-xl-center text-break"
                         asp-area="Admin"
                         asp-controller="LrProducts"
                         asp-action="Add"
                         asp-route-id="@product.Id">Update</a>                                                                     
                      }
                      else
                      {
                      <a asp-controller="LrProducts" asp-action="Edit" asp-route-id="@product.Id" class="btn btn-primary text-xl-center  text-break">favorit♥</a>
                      <a class="btn btn-success text-xl-center text-break"
                         asp-controller="LrProducts"
                         asp-action="ForBag"
                         asp-route-id="@product.Id">Bag</a>                                              
                      }
                  </li>
              </ul>
          </div>

      </div>
  </div>
      }
  </div>

DnaFragment/Views/LrProducts/AllProductsByCategory.cshtml
@model List<LrProductServiceModel>

@{ ViewBag.Title = "Products by category"; }

<hr class="bg-primary w-75">
@if (Model.Count == 1 && !User.IsAdmin())
 {
    <form class="mx-auto w-50" size="3">
      <div class="alert alert-secondary alert-dismissible fade show  ">
          <strong>We expect delivery of a new batch from the plant in Germany.</strong><button type="button" class="close btn-outline-danger" data-dismiss="alert">&times;</button>
      </div>
    </form>
 }
<hr class="bg-primary w-50">
<h2 class="text-center mt-2">@ViewBag.Title</h2>

@if (Model.Count != 1)
{
    <h1 class="text-center mt-2 text-success">▪</h1>
    <h1 class="text-center mt-2 text-white">▪</h1>
    <h1 class="text-center mt-2 text-white">▪</h1>
    <h1 class="text-center mt-2 text-white">▪</h1>
}
else
{
    <h1 class="text-center mt-2 text-danger">▪</h1>
    <h1 class="text-center mt-2 text-secondary">▪</h1>
    <h1 class="text-center mt-2 text-secondary">▪</h1>
    <h1 class="text-center mt-2 text-secondary">▪</h1>
}
<form class="mx-auto w-50" size="3">
 @if (Model.Count == 1)
 {
<img src="https://img5.goodfon.com/wallpaper/nbig/0/fb/devushka-shatenka-shliapa-priroda-lug-tsvety-peizazh.jpg"
         class="card-img-top img-fluid card-image rounded-left " data-toggle="tooltip"
         data-placement="bottom">  
 }
 else
 {
     int i = 1;
     foreach (var photo in Model[0].Photos)
     {
       @if (Model[1].CategoryId == i)
       {
         <img src=@photo
         class="card-img-top img-fluid card-image rounded-left " data-toggle="tooltip"
         data-placement="bottom">
       }
         i++;
     }
    
 }
@if (Model.Count != 1)
{
    <h1 class="text-center mt-2 text-white">▪</h1>
    <h1 class="text-center mt-2 text-white">▪</h1>
    <h1 class="text-center mt-2 text-white">▪</h1>
    <h1 class="text-center mt-2 text-white">▪</h1>
}
else
{
    <h1 class="text-center mt-2 text-secondary">▪</h1>
    <h1 class="text-center mt-2 text-secondary">▪</h1>
    <h1 class="text-center mt-2 text-secondary">▪</h1>
    <h1 class="text-center mt-2 text-secondary">▪</h1>
}
@if (Model.Count != 1)
{
    for (int i = 1; i < Model.Count; i++)
    {

        <div class="form-group col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
            <a class="btn btn-block btn-outline-warning btn-sm font-italic text-break"
               asp-controller="LrProducts"
               asp-action="Details"
               asp-route-id="@Model[i].Id">
                @Model[i].Model
            </a>
            <img src="@Model[i].PictureUrl"
                 class="card-img-top img-fluid card-image rounded-left " data-toggle="tooltip"
                 data-placement="bottom" title="LR">
            <a class="btn btn-block btn--secondary text-white text-lg-center"
               asp-controller="LrProducts"
               asp-action="Details"
               asp-route-id="@Model[i].Id">
                @Model[i].Price lv.
            </a>
        
            <h4 class="text-center mt-2 text-white ">▪</h4>
            <h4 class="text-center mt-2 text-success ">▪</h4>
            <h4 class="text-center mt-2 text-white ">▪</h4>
        
        </div>
    }
    <hr class="bg-white w-50">
}
</form>

DnaFragment/Views/LrProducts/Bag.cshtml
@model AddNewInfoProductFormModel

@{ ViewBag.Title = "Shop♡"; }

<hr class="bg-primary w-75">
 <div class="alert alert-secondary mx-auto w-50 small ">
        <strong>За вашите поръчки използваме услугите на Speedy с включена цена 3.90 лв.</strong><button type="button" class="close text-white" data-dismiss="alert">&times;</button>
    </div>
    <div class="alert alert-secondary mx-auto w-50 small ">
        <strong>За поръчки над 5 артикула печелите отстъпка от крайната цена.</strong><button type="button" class="close text-white" data-dismiss="alert">&times;</button>
    </div>
    <div class="alert alert-secondary mx-auto w-50 small ">
        <strong>При баланс 60лв. печелите 1 Lr point.</strong><button type="button" class="close text-white" data-dismiss="alert">&times;</button>
    </div>
<hr class="bg-primary w-50">
<h2 class="text-center mt-2">@ViewBag.Title</h2>
@if (Model.Products != null)
{
<h1 class="text-center mt-2 text-white">▪</h1> 
}
else
{
<h1 class="text-center mt-2 text-danger">▪</h1>
}
<form class="mx-auto w-75" method="post">
    <div class="form-group w-100">
        <!--Mask color-->
        <div class="view ">
            <!--Video source-->
            <video class="video-fluid w-100" autoplay loop muted>
                <source src="https://mdbootstrap.com/img/video/animation-intro.mp4" type="video/mp4" />
            </video>
            <div class="mask rgba-purple-slight"></div>
        </div>
    </div>  
          
    @if(!Model.Products.Any())
    {
        <h4 class="text-center">No products found by the given criteria!</h4>
    }
<div class="form-group mx-auto w-100 ">
    <ul class="list-group list-group-flush ">
        <li class="list-group-item text-xl-center text-white bg-primary">TOTAL: @Model.Amount lv.</li>
        <li class="list-group-item text-xl-center text-white bg-primary">- @Model.PercentageDiscount %</li>
    </ul>    
    @if (Model.Products.Any() && Model.ProductsCountIsNotEmpty)
    {
    <button class="btn btn-outline-primary small w-100" asp-controller="LrProducts" asp-action="BagsInformation">Complete the Order</button>
    }   
</div>
   @if (Model.Products.Any())
    { 
     <h1 class="text-center mt-2 text-success">_</h1>
    <div class="form-group mx-auto w-25">      
        <input asp-for="ProductsCount" type="text" class="form-control mx-auto w-50" placeholder="" id="productsCount-input " aria-label="Example text with two button addons">
        <div class="form-group mx-auto w-50">
           @foreach (var product in Model.Products)
           {
               if (product.Bought)
               {
                    <p1 class="text-success text-center ">▪</p1>
               }
               else
               {
                    <p1 class="text-white text-center ">▪</p1>
               }
           }
        </div>
    </div>
    }
   
  <div class="row justify-content-center ">
 @if (Model.Products != null)
 {

    @foreach (var product in Model.Products)
    {

        <div class=" col-md-4 ">
            <div class="form-group card mb-3 ">
        
                <img class="card-img-top" src="@product.PictureUrl" alt="@product.Price" title="@product.Model">
        
                <ul class="list-group list-group-flush ">
                    <li class="list-group-item text-xl-center text-white">@product.Price lv.</li>
                </ul>
                <div class="input-group mb-3 small ">
                    <button class="btn btn-outline-danger w-50" type="submit" asp-controller="LrProducts" asp-action="DeleteFromTheBag" asp-route-id="@product.Id">Delete</button>
                    <button class="btn btn-success w-50 " type="submit" asp-controller="LrProducts" asp-action="Bag" asp-route-id="@product.Id">$hop</button>
        
                </div>
        
            </div>
        </div>
    }
 }

    </div>
</form>

DnaFragment/Views/LrProducts/BagsInformation.cshtml
@model BagsInformationsModel

@{ ViewBag.Title = "Delivery Information"; }

<hr class="bg-primary w-75">
<hr class="bg-primary w-50">
<hr class="bg-primary w-25">
<h2 class="text-center mt-2">@ViewBag.Title</h2>

<div class="row mt-4 mb-4">

    <form class="mx-auto w-50" method="get">

        <div class="form-group mx-auto ">
            <p1 class="text-success">▪▪▪▪</p1>
            <img class="d-block w-100 " src="https://images.template.net/wp-content/uploads/2014/10/face-sketche18.jpg" alt="Responsive image">
        </div>

        <div class="form-group">
            <label asp-for="City">City</label>
            <input asp-for="City" type="text" class="form-control" id="city-input">
            <span asp-validation-for="City" class="small text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Address">Address</label>
            <input asp-for="Address" type="text" class="form-control" id="address-input">
            <span asp-validation-for="Address" class="small text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PhoneNumber">Phone number</label>
            <input asp-for="PhoneNumber" type="text" class="form-control" id="phoneNumber-input">
            <span asp-validation-for="PhoneNumber" class="small text-danger"></span>
        </div>     

        <button type="submit" class="btn btn-block btn-primary">Add Information</button>
    </form>
</div>

DnaFragment/Views/LrProducts/Details.cshtml
@model LrProductDetailsServiceModel

@{ ViewBag.Title = "Product"; }

<hr class="bg-primary w-75">
<hr class="bg-primary w-50">
<h2 class="text-center mt-2">@ViewBag.Title</h2>

@if (Model != null)
{   
    <h1 class="text-center mt-2 text-white">▪</h1>  
}
else
{    
    <h1 class="text-center mt-2 text-secondary">▪</h1>
}
<form class="mx-auto w-50" size="3">
 @if (Model == null)
{
    <img src="https://img5.goodfon.com/wallpaper/nbig/0/fb/devushka-shatenka-shliapa-priroda-lug-tsvety-peizazh.jpg"
         class="card-img-top img-fluid card-image rounded-left " data-toggle="tooltip"
         data-placement="bottom">
    <ul class="list-group list-group-flush small">
        <li class="list-group-item text-center  "><h class="text-danger">•</h> Моля заредете базата от данни с продукти по категории!</li>
    </ul>
}
else
{
     <ul class="list-group list-group-flush ">
         <li class="list-group-item text-center font-italic text-xl-center text-warning ">@Model.Model  @Model.PackagingVolume ml.</li>
    </ul>
    <img class="card-img-top" src="@Model.PictureUrl">
   
    <a class="btn btn-block btn--secondary text-white text-lg-center"
       asp-controller="LrProducts"
       asp-action="All">
        @Model.Price lv.
    </a>
    <ul class="list-group list-group-flush ">
        <li class="btn-group btn-group d-flex justify-content-center " role="group" aria-label="Button group example">
            <a asp-controller="LrProducts" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-outline-light text-xl-center  text-break">favorit♥</a>
            <a class="btn btn-outline-success text-xl-center text-break"
               asp-controller="LrProducts"
               asp-action="ForBag"
               asp-route-id="@Model.Id">
                Bag
            </a>
        </li>
    </ul>
}
<hr class="bg-primary w-100">
@if (Model != null)
{   
<h class="text-xl-left font-italic text-primary">✦ ChemicalIngredients</h>
}
else
{   
<h1 class="text-xl-left font-italic text-secondary">✦ ChemicalIngredients</h1>
}
    <ul class="list-group list-group-flush ">
        <li class="list-group-item text-left  text-break ">@Model.ChemicalIngredients</li>
    </ul> 
    <hr class="bg-primary w-100">
    <h class="text-xl-left font-italic text-primary">✦ Description</h>
    <ul class="list-group list-group-flush ">
        <li class="list-group-item text-left  text-break"> @Model.Description</li>       
    </ul>
    <hr class="bg-primary w-100">
</form>

DnaFragment/Views/LrProducts/Favorits.cshtml
@model List<LrProductDetailsServiceModel>

@{ ViewBag.Title = "Favorits♡"; }

<hr class="bg-primary w-75">
<hr class="bg-primary w-50">
<hr class="bg-primary w-25">
<h2 class="text-center mt-2">@ViewBag.Title</h2>
@if (Model.Any())
{
    <h1 class="text-center mt-2 text-success">▪</h1>
}
else
{
    <h1 class="text-center mt-2 text-danger">▪</h1>
}
<div class="container w-75">
    <div id="carouselExampleSlidesOnly " class="carousel slide " data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item">
                <img src="https://i.pinimg.com/originals/16/7d/45/167d45c1fdb2cc5c50f6fed50e76e46b.jpg" class="card-img-top " alt="...">
            </div>
            <div class="carousel-item active">
                <img src="https://www.susannacapriata.com/assets/images/audi-lr-1920x1080.jpg" class="card-img-top " alt="...">
            </div>
            <div class="carousel-item">
                <img src="https://s1.dmcdn.net/v/KsXYS1VhBKDYsqVrt/x1080" class="card-img-top " alt="...">
            </div>
        </div>
    </div>
</div>

<hr class="bg-primary w-25">
<hr class="bg-primary w-50">
<hr class="bg-primary w-75">

@if (!Model.Any())
{
    <h3 class="text-center">No products found by the given criteria!</h3>
}
<form class="mx-auto w-100" method="post">
    <div class="row justify-content-center">
        @foreach (var product in Model)
        {
            <div class=" col-md-4 ">
                <div class="form-group card mb-3 ">
                    <a class="btn btn-outline-warning text-sm text-break"
                       asp-controller="LrProducts"
                       asp-action="Details"
                       asp-route-id="@product.Id">
                        @product.Model
                    </a>
                    <img class="card-img-top" src="@product.PictureUrl" alt="@product.Price">
                    <div class="card-body text-center">
                        <ul class="list-group list-group-flush ">
                            <li class="list-group-item text-xl-center text-white">@product.Price lv.</li>
                        </ul>
                        <ul class="list-group list-group-flush ">
                            <li class="btn-group btn-group d-flex justify-content-center " role="group" aria-label="Button group example">
                                <a class="btn btn-success text-break text-white text-xl-center"
                                   asp-controller="LrProducts"
                                   asp-action="Details"
                                   asp-route-id="@product.Id">
                                    $hop
                                </a>
                            </li>
                        </ul>
                    </div>

                </div>
            </div>}
    </div>
</form>