DnaFragment/Areas/Admin/Controllers/LrUsersController.cs
namespace DnaFragment.Areas.Admin.Controllers
{
    using DnaFragment.Services.Mail;
    using DnaFragment.Services.Users;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class LrUsersController : AdminController
    {
       
        private readonly IUsersService usersService;
        private readonly ISendMailService sendMail;

        public LrUsersController(IUsersService usersService, ISendMailService sendMail)
        {
            this.usersService = usersService;            
            this.sendMail = sendMail;            
        }
        public IActionResult All(byte sort)
        {           
            var users =  usersService.UsersStatistics(sort);

            return View(users);
        }                    

        public IActionResult ShippingDelivery(string userId)
        {
            var users = usersService.ShippingOrders(userId);

            return View(users);
        }
        [Authorize]
        public IActionResult SendingTheRequest(int bagId)
        {
            usersService.Received(bagId);
            sendMail.SmsMessanger("0876408508","Очквайте доставка до 1 ден и потвърдете с кода за идентификация на поръчката!DnaFragment♡");
            return Redirect("/Admin/LrUsers/ShippingDelivery");
        }

    }
}

DnaFragment/Areas/Admin/Views/LrUsers/All.cshtml
@model List<LrUsersStatisticsFormModel>
@{ ViewBag.Title = "LR Users"; }

<hr class="bg-primary w-75">
<hr class="bg-primary w-50">
<h2 class="text-center mt-2 text-white">@ViewBag.Title</h2>
<h1 class="text-center mt-2 text-success">▪</h1>

<form class="mx-auto w-75">

    <img class="d-block w-100 " src="https://chamlinlaw.com/wp-content/uploads/2016/01/Assault_CR.jpg" alt="Responsive image">

    @if (!Model.Any())
    {

        <div class="form-group ">
            <ul class="list-group list-group-flush ">
                <li class="list-group-item text-center text-success">
                    The database is activated!
                    <hr class="bg-success w-75">
                </li>
            </ul>
        </div>
    }
    else
    {
        <div class="btn-group btn-group-sm d-flex justify-content-center" role="group" aria-label="Button group example">
            <a class="btn  text-primary text-left bg-white"
               asp-controller="LrUsers"
               asp-action="All"
               asp-route-sort=1>SORT BY NAME</a>
            <a class="btn  text-primary text-right bg-white"
               asp-controller="LrUsers"
               asp-action="All"
               asp-route-sort=2>SORT BY ID</a>
        </div>
    }
    @for (int i = 0; i < Model.Count; i++)
    {

        <div class="form-group">
            @if (Model[i].IsSuperUser)
            {
                <hr class="bg-info w-50">
            }
            else if (Model[i].Id != null)
            {
                <hr class="bg-success w-50">
            }
            else if (Model[i].IsDanger)
            {
                <hr class="bg-danger w-50">
            }
            else
            {
                <hr class="bg-white w-50">
            }
            <ul class="list-group list-group-flush ">
                <li class="list-group-item text-center text-break">@Model[i].Username</li>
                <li class="list-group-item text-center text-break">@Model[i].LrPoints</li>
                <li class="list-group-item text-center text-break">@Model[i].Email</li>
                <li class="list-group-item text-center text-break">@Model[i].PhoneNumber</li>
                <li class="list-group-item text-center">Nc:[ @Model[i].CategoriesVisitsCount]</li>
                <li class="list-group-item text-center">Np:[ @Model[i].ProductsVisitsCount ]</li>
                <li class="btn-group btn-group-sm d-flex justify-content-center" role="group" aria-label="Button group example">
                    @if (Model[i].Id != null)
                    {
                        <a class="btn btn-outline-primary "
                           asp-area="Admin"
                           asp-controller="Messages"
                           asp-action="Add"
                           asp-route-lrUserId="@Model[i].Id">Message</a>
                        <a class="btn btn-outline-primary "
                           asp-area="Admin"
                           asp-controller="Messages"
                           asp-action="SendMail"
                           asp-route-userId="@Model[i].Id">Email</a>
                        <a class="btn btn-outline-primary "
                           asp-area="Admin"
                           asp-controller="Messages"
                           asp-action="Sms"
                           asp-route-userId="@Model[i].Id">Sms</a>
                        <a class="btn btn-danger " title="The feature will immediately delete all your account data except the accumulated points!"
                           asp-area="DnaFragmentControllers"
                           asp-controller="LrUsers"
                           asp-action="DeleteUser"
                           asp-route-userId="@Model[i].Id">Delete DB</a>
                        <a class="btn btn-success " title="The feature will immediately delete all your account data except the accumulated points!"
                           asp-area="Admin"
                           asp-controller="LrUsers"
                           asp-action="ShippingDelivery"
                           asp-route-userId="@Model[i].Id">Orders</a>
                    }
                </li>
            </ul>
        </div>

    }

</form>

DnaFragment/Areas/Admin/Views/LrUsers/Index.cshtml
<h1>Hello from the Admin!</h1>

DnaFragment/Areas/Admin/Views/LrUsers/ShippingDelivery.cshtml
@model List<UserOrderFormModel>
@{ ViewBag.Title = "LR Users"; }

<hr class="bg-primary w-75">
<hr class="bg-primary w-50">
<h2 class="text-center mt-2 text-white">@ViewBag.Title</h2>
<h1 class="text-center mt-2 text-success">▪</h1>

<form class="mx-auto w-75">

    <img class="d-block w-100 " src="https://chamlinlaw.com/wp-content/uploads/2016/01/Assault_CR.jpg" alt="Responsive image">
    @if (Model != null)
    {
        @for (int i = 0; i < Model.Count; i++)
        {
            <div class="form-group">
                <hr class="bg-success w-50">
                <ul class="list-group list-group-flush ">
                    <li class="list-group-item text-center text-break">@Model[i].FullName</li>
                    <li class="list-group-item text-center text-break">@Model[i].Total</li>
                    <li class="list-group-item text-center text-break">@Model[i].City</li>
                    <li class="list-group-item text-center text-break">@Model[i].ShippingAddress</li>
                    <li class="list-group-item text-center text-break">@Model[i].PhoneNumber</li>
                    <li class="list-group-item text-center">@Model[i].DeliveryNumber</li>
                    <li class="list-group-item text-center">@Model[i].BagProducts</li>
                    <li class="btn-group btn-group-sm d-flex justify-content-center" role="group" aria-label="Button group example">
                        
                            <a class="btn btn-outline-primary "
                               asp-area="Admin"
                               asp-controller="LrUsers"
                               asp-action="SendingTheRequest"
                               asp-route-bagId="@Model[i].BagId">Complete</a>

                        
                    </li>
                </ul>
            </div>

        }
    }
    </form>